version: '3'

tasks:
  build:
    cmds:
      - go build -v -o bin/sober-roadmap main.go
    desc: Build the sober-roadmap binary

  run: # run the server
    cmds:
      - go run ./main.go
    desc: Run the server

  test:
    cmds:
      - go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
    desc: Run all tests with gotestfmt

  fmt:
    cmds:
      - go fmt ./...
    desc: Format the Go code

  vet:
    cmds:
      - go vet ./...
    desc: Vet the Go code

  lint:
    cmds:
      - golangci-lint run
    desc: Run static analysis

  bench:
    cmds:
      - go test -bench .
    desc: Run benchmarks

  update:
    cmds:
      - go get -u
      - go mod tidy
    desc: Update dependencies

  docker:
    cmds:
      - docker build -t jonesrussell/sober-roadmap .
    desc: Build Docker image

  clean:
    cmds:
      - rm -rf ./bin
    desc: Clean up generated files

  generate:
    cmds:
      - templ generate
    desc: Generate files based on templates

  default:
    desc: Run default tasks
    deps:
      - clean
      - fmt
      - vet
      - lint
      - generate
      - test
      - build
