// components/svg.go
package components

import (
	"bytes"

	svg "github.com/ajstarks/svgo"
)

func SVG(content func(canvas *svg.SVG)) string {
	var buf bytes.Buffer
	canvas := svg.New(&buf)
	canvas.Start(1118, 1631, `xmlns="http://www.w3.org/2000/svg"`, `xmlns:xlink="http://www.w3.org/1999/xlink"`, `viewBox="-697 -223 1118 1631"`, `style="font-family: balsamiq"`, `version="1.1"`)
	canvas.Title("Sobriety Roadmaps")
	canvas.Desc("Generated by svgo")

	// Call the content function to add SVG elements
	content(canvas)

	canvas.End()
	return buf.String()
}
