name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Run templ generate
      run: templ generate

    - name: Install dependencies
      run: go get ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Install npm dependencies
      run: npm install
      working-directory: tailwind/

    - name: Build CSS for Production
      run: npm run build-css-prod
      working-directory: tailwind/

    - name: Generate Static Site
      env:
        BASE_PATH: /sober
      run: go run main.go -generate

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
